[local]
localhost

[mongodb]
mongodb.amireddyravi.space

[redis]
redis.amireddyravi.space

[mysql]
mysql.amireddyravi.space

[rabbitmq]
rabbitmq.amireddyravi.space

[catalogue]
catalogue.amireddyravi.space

[user]
user.amireddyravi.space

[cart]
cart.amireddyravi.space

[shipping]
shipping.amireddyravi.space

[payment]
payment.amireddyravi.space

[frontend]
frontend.amireddyravi.space